### ISSUE TITLE
Missing package: syft

### ISSUE THREAD

**Issue by robert-wagner** [bennuttall/piwheels#147]
Missing package
Package name: syft
Link to PyPI page: https://pypi.org/project/syft
Link to piwheels page: https://www.piwheels.org/project/syft
Version: e.g. 0.1.7a1 - 0.1.14a1
Python version: e.g. all
More information:

The last 8 versions of syft (two months) are missing from piwheels but are available on PyPi. There are no successful or failed builds displayed

**Comment by bennuttall** [comment]
We're not building anything at the moment while we perform an upgrade. Will be up and running soon!

**Comment by bennuttall** [comment]
Reopening - will check this has built when we are back in operation

**Comment by robert-wagner** [comment]
@bennuttall The reason I closed this is that a user of pysyft said they were able to clone on raspberry pi so I thought it was fixed

**Comment by bennuttall** [comment]
The issue is still valid, we don't have wheels of recent versions of this package.
